todo/config/routes.rb
Rails.application.routes.draw do
  resources :users, except: [:edit, :update, :destroy] do
    resources :tasks, only: [:new, :create, :destroy]
  end

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  root 'users#new'

end

todo/app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :user

  validates :content, presence: true
  validates :user_id, presence: true
end

todo/app/models/user.rb
class User < ActiveRecord::Base
  has_many :tasks
  has_secure_password


  validates :name, presence: true
  validates :email, presence: true
end

todo/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

todo/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    @user = User.find_by(email: params[:session][:email])
    if @user && @user.authenticate(params[:session][:password])
      session[:user_id] = @user.id
      redirect_to user_path(@user)
    else
      redirect_to login_path
    end
  end

  def destroy
    session.delete(:user_id)
    redirect_to login_path
  end
end

todo/app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  def new
    @user = User.find(params[:user_id])
    @task = Task.new
  end

  def create
    @user = User.find(params[:user_id])
    @task = Task.new(task_params, user_id: @user.id)
    @task.user = @user
    if @task.save
      redirect_to user_path(@user)
    else
      render :new
    end
  end

  def destroy
    @user = User.find(params[:user_id])
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to user_path(@user)
  end

  def task_params
    params.require(:task).permit(:content)
  end
end

todo/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to login_path
    else
      redirect_to new_user_path
    end
  end

  def user_params
    params.require(:user).permit(:name, :email, :password)
  end

end

todo/app/helpers/application_helper.rb
module ApplicationHelper
end

todo/app/helpers/session_helper.rb
module SessionHelper
end

todo/app/helpers/task_helper.rb
module TaskHelper
end

todo/app/helpers/user_helper.rb
module UserHelper
end

todo/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Todo</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <% if session[:user_id] %>
    <%= link_to "Logout", logout_path, method: 'delete' %>
  <% else %>
    <%= link_to "Login", login_path %>
  <% end %>
  <%= yield %>

</body>
</html>

todo/app/views/tasks/new.html.erb
<%= form_for([@user, @task]) do |f| %>
  <%= f.label :content %>
  <%= f.text_field :content, placeholder: 'Task' %>
  <%= f.submit 'Submit' %>
<% end %>

todo/app/views/users/index.html.erb
<% @users.each do |user| %>
  <%= link_to "#{user.name}", user_path(user)  %>
<% end %>

todo/app/views/users/new.html.erb
<h2>Signup</h2>

<%= form_for @user do |f| %>
  <div>
    <%= f.label :name %>
    <%= f.text_field :name, placeholder: 'Name' %>
  </div>
  <div>
    <%= f.label :email %>
    <%= f.text_field :email, placeholder: "Email" %>
  </div>
  <div>
    <%= f.label :password %>
    <%= f.password_field :password, placeholder: 'Password' %>
  </div>
  <div>
    <%= f.submit 'Submit' %>
  </div>
<% end %>

todo/app/views/users/show.html.erb
<div>
  <% @user.tasks.each do |task| %>
    <div><%= task.content %></div>
    <div><%= link_to 'Delete Task', [@user, task], method: 'delete'  %></div>
  <% end %>
</div>
<div>
  <%= link_to 'New Task', new_user_task_path(@user)  %>
</div>